--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 05. 09. 9:19:45
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS carproducts;

CREATE DATABASE IF NOT EXISTS carproducts
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE carproducts;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) DEFAULT NULL,
  lastName VARCHAR(255) DEFAULT NULL,
  username VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `loggedinusers`
--
CREATE TABLE IF NOT EXISTS loggedinusers (
  id INT(11) NOT NULL AUTO_INCREMENT,
  dateTime DATETIME DEFAULT NULL,
  userId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE loggedinusers 
  ADD CONSTRAINT FK_loggedinusers_users_id FOREIGN KEY (userId)
    REFERENCES users(id);

--
-- Create table `products`
--
CREATE TABLE IF NOT EXISTS products (
  id INT(11) NOT NULL AUTO_INCREMENT,
  productName VARCHAR(255) DEFAULT NULL,
  quantity INT(11) DEFAULT NULL,
  price INT(11) DEFAULT NULL,
  isInStock VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 33,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `cart`
--
CREATE TABLE IF NOT EXISTS cart (
  id INT(11) NOT NULL AUTO_INCREMENT,
  userId INT(11) DEFAULT NULL,
  productId INT(11) DEFAULT NULL,
  shoppingDate DATE DEFAULT NULL,
  bought TINYINT(4) DEFAULT NULL,
  quantity INT(11) DEFAULT NULL,
  price INT(11) DEFAULT NULL,
  shoppingId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE cart 
  ADD CONSTRAINT FK_cart_loggedinusers_id FOREIGN KEY (shoppingId)
    REFERENCES loggedinusers(id);

--
-- Create foreign key
--
ALTER TABLE cart 
  ADD CONSTRAINT FK_cart_products_id FOREIGN KEY (productId)
    REFERENCES products(id);

--
-- Create foreign key
--
ALTER TABLE cart 
  ADD CONSTRAINT FK_cart_users_id FOREIGN KEY (userId)
    REFERENCES users(id);

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Admin', 'Bácsi', 'admin', '123', 'adminba@gmail.com'),
(2, 'Kovács', 'Ferenc', 'kferi', 'feri123', 'kferenc@gmail.com'),
(3, 'Nagy', 'Zsolt', 'nzsolti', '123456', 'zsoltinagy@gmail.com');

-- 
-- Dumping data for table products
--
INSERT INTO products VALUES
(1, 'Féktárcsa', 10, 3500, '1'),
(2, 'Téli gumi', 0, 6500, '0'),
(3, 'Nyáru gumi', 4, 5500, '1'),
(8, 'BBS Felni - 17''', 8, 45000, '16'),
(9, 'Fékpofa', 32, 13500, '5'),
(10, 'Ülések', 4, 37000, '16'),
(11, 'Katalizátor', 2, 553000, '1'),
(16, 'Csavarok', 10000, 750, '3456'),
(17, '5Zigen Felni', 18, 35000, '20'),
(18, 'Csavarhúzó', 75, 2500, '114'),
(19, 'Kipufogócső', 80, 750000, '160'),
(20, 'Hátsó lámpák', 67, 23500, '55'),
(21, 'Ablaktörlők', 42, 38000, '12'),
(22, 'Prémium olaj', 22, 7500, '75'),
(23, 'Plüss dobókocka', 3, 1800, '17'),
(24, 'Benzines kanna', 6, 7500, '5'),
(25, 'Fék olaj', 65, 12300, '3'),
(26, 'Kormány huzat - Piros', 5, 4500, '2'),
(27, 'Kormány huzat - Kék', 10, 4200, '1'),
(28, 'Kormány huzat - Fekete', 6, 4500, '10'),
(31, 'Motorháztető', 12, 67000, '60');

-- 
-- Dumping data for table loggedinusers
--
-- Table carproducts.loggedinusers does not contain any data (it is empty)

-- 
-- Dumping data for table cart
--
-- Table carproducts.cart does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;