--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 05. 15. 9:31:14
-- Server version: 5.5.5-10.4.18-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS carproducts;

CREATE DATABASE IF NOT EXISTS carproducts
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE carproducts;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) DEFAULT NULL,
  lastName VARCHAR(255) DEFAULT NULL,
  username VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  number INT(11) DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `loggedinusers`
--
CREATE TABLE IF NOT EXISTS loggedinusers (
  id INT(11) NOT NULL AUTO_INCREMENT,
  dateTime DATETIME DEFAULT NULL,
  userId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE loggedinusers 
  ADD CONSTRAINT FK_loggedinusers_users_id FOREIGN KEY (userId)
    REFERENCES users(id);

--
-- Create table `products`
--
CREATE TABLE IF NOT EXISTS products (
  id INT(11) NOT NULL AUTO_INCREMENT,
  productName VARCHAR(255) DEFAULT NULL,
  quantity INT(11) DEFAULT NULL,
  price INT(11) DEFAULT NULL,
  isInStock VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 53,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `cart`
--
CREATE TABLE IF NOT EXISTS cart (
  id INT(11) NOT NULL AUTO_INCREMENT,
  userId INT(11) DEFAULT NULL,
  productId INT(11) DEFAULT NULL,
  shoppingDate DATE DEFAULT NULL,
  bought TINYINT(4) DEFAULT NULL,
  quantity INT(11) DEFAULT NULL,
  price INT(11) DEFAULT NULL,
  shoppingId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE cart 
  ADD CONSTRAINT FK_cart_loggedinusers_id FOREIGN KEY (shoppingId)
    REFERENCES loggedinusers(id);

--
-- Create foreign key
--
ALTER TABLE cart 
  ADD CONSTRAINT FK_cart_products_id FOREIGN KEY (productId)
    REFERENCES products(id);

--
-- Create foreign key
--
ALTER TABLE cart 
  ADD CONSTRAINT FK_cart_users_id FOREIGN KEY (userId)
    REFERENCES users(id);

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(4, 'Farkas', 'Bence', 'fbence', '$2b$10$mQiU.NDNwVrr7Cdk/uozD.uhGR.94q9GjhvdF5Hje1xdpXKRHoSRW', 'farkas.bence03@gmail.com', 0),
(5, 'Admin', 'Bácsi', 'admin', '$2b$10$cwN/PnDYR98OG/wEf7j.cuFgg81RQ4WpVaWLGD7PhVzc3UFvyqYd2', 'adminba@gmail.com', 1),
(6, 'Kovács', 'Eszter', 'eszti', '$2b$10$UPtmRq6s80oTgdso7yylzeXkcmisESvXGGpQntuKqKJNa.x5D7Dhy', 'k.eszter@gmail.com', 0);

-- 
-- Dumping data for table products
--
INSERT INTO products VALUES
(35, 'Ablaktörlők', 15, 5290, '2', 'Az ilyen típusú lapos ablaktörlővel nem felszerelt régebbi járművek számára a Bosch Aerotwin Retrofit terméket kínál, amely egy speciális adapterrel felszerelve néhány másodperc alatt kicseréli a hagyományos ablaktörlőket. Így egyre több járművezető élvez'),
(36, 'Akkumulátor', 7, 23760, '1', 'Autó akkumulátor 45Ah BOSCH'),
(37, 'BBS Felni', 4, 82883, '16', 'Ezüst színű BBS Felni. Elérhető méretek: 17'' 18'' 19'' 20'''),
(38, 'Benzines kanna', 30, 6990, '5', '5 Literes benzines kanna'),
(39, 'Csavarok', 455, 115, '1650', 'Tex csavarok M 4,2/16 hegyes fejjel'),
(40, 'Fékpofa', 60, 1000, '87', '[SUZUKI / GAMMA] - FÉKPOFA GRT.HÁTSÓ TS125'),
(41, 'Féktárcsa', 10, 25910, '22', 'Hella Pagid féktárcsa HELLA PAGID 8DD 355 116-311'),
(42, 'Gyújtógyertya', 8, 8390, '16', 'NGK Gyújtógyertya ILZKR7D8'),
(43, 'Hátsó lámpák', 10, 6190, '2', 'AVC Hátsólámpa IFA Jobb (33541)'),
(44, 'Katalizátor', 5, 56401, '3', 'A katalizátor a motor azon része, amelyik a jármű káros anyag kibocsájtását csökkenti. Elhelyezkedésileg a kipufogó rendszerben találjuk a csőrendszerbe iktatva, vagy közvetlenül a torokba helyezve.'),
(45, 'Kipufogócső', 30, 7101, '10', 'Aluplatírozott acél kipufogócső, DX53+AS120, Falvastagság: 1,5mm, Hossz: 2m'),
(46, 'Lökhárító', 10, 8150, '80', 'HONDA Jazz Hatchback (GD, GE3, GE2)'),
(47, 'Plüss dobókocka', 8, 1300, '10', 'Tökéletes autó kiegészítők'),
(48, 'Ventilátor', 7, 18990, '12', 'Xiaomi Mi Smart Standing Fan 2 Lite (1C) (PYV4007GL)'),
(49, 'Visszapillantó tükör', 40, 8350, '10', 'Lampa Középső visszapillantó tükör univerzális 65498');

-- 
-- Dumping data for table loggedinusers
--
-- Table carproducts.loggedinusers does not contain any data (it is empty)

-- 
-- Dumping data for table cart
--
-- Table carproducts.cart does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;